// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Direct Supabase URL for edge cases, but we prioritize the proxied URL to bypass JIO blocking
const _SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Route all requests through the proxy created in vite.config.ts/netlify.toml/vercel.json
// This bypasses ISP-level DNS blocking of supabase.co domains (e.g., JIO networks in India)
const PROXIED_SUPABASE_URL = typeof window !== 'undefined'
  ? `${window.location.origin}/supabase-api`
  : _SUPABASE_URL;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(PROXIED_SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});